# fly.toml app configuration file generated for full-stack-open-pokedex-fs on 2024-08-21T12:21:11+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#


app = 'full-stack-open-pokedex-fs'
primary_region = 'arn'


[env]
  PORT = "3000"

[build]
  strategy = "canary"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'

[[http_service.checks]]
  grace_period = "10s"
  interval = "15s"
  method = "GET"
  timeout = "10s"
  path = "/health"