name: Check code and deploy

on:
  push:
    branches:
      - main

  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  deployment:
    runs-on: ubuntu-20.04
    concurrency: deploy-group
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '19.9.0'
      - name: Configure environment
        run: npm install
      - name: Eslint
        run: npm run eslint
      - name: Tests
        run: npm run test
      - name: Install playwright deps
        run: npx playwright install --with-deps
      - name: Run e2e tests
        run: npm run test:e2e
      
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy to fly
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        if: ${{ github.event_name == 'push' }}
      
      - name: Job succeed
        uses: rjstone/discord-webhook-notify@v1.0.4

        if: ${{ success() && github.event_name == 'push' }}
        with:
          severity: info
          details: A new commit was deployed successfully by ${{ github.event.pull_request.user.login }}
          webhookUrl: ${{ secrets.FS_WEBHOOK }}


      - name: Job failed
        uses: rjstone/discord-webhook-notify@v1.0.4

        if: ${{ failure() }}
        with:
          severity: error
          details: Deployment tests of commit ${{ github.event.pull_request.head.sha }} failed.
          webhookUrl: ${{ secrets.FS_WEBHOOK }}

  tag_release:

    needs: [deployment]
    runs-on: ubuntu-20.04
    permissions:
      contents: write


    steps:

      - uses: actions/checkout@v4
        with: 
          ref: ${{ github.event.pull_request.merge_commit_sha }}

      - name: Use semantic version autoincrement
        uses: anothrNick/github-tag-action@1.64.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
        if: github.event_name == 'push' && !contains(join(github.event.commits.*.message, ' '), '#skip')
