on:
  schedule:
    - cron: '30 5 * * *'

jobs:
  health-check:
    runs-on: ubuntu-20.04

    steps:
      - name: URL Health Check
        uses: jtalk/url-health-check-action@v4
        with:
          url: http://doesnotexist.kyselykeskus.fi # testing that with invalid url will fail
          

